export { default as Dashboard } from './menu-16/sv-dashboard-icon.vue'
export { default as Dot } from './menu-16/sv-dot-icon.vue'
export { default as Plugins } from './menu-16/sv-plugins-icon.vue'
export { default as Flag } from './menu-16/sv-flag-icon.vue'
export { default as Bug } from './menu-16/sv-bug-icon.vue'