export { default as Adjust } from './other-16/sv-adjust-icon.vue'
export { default as MenuOpen } from './other-16/sv-menu-open-icon.vue'
export { default as Search } from './other-16/sv-search-icon.vue'
export { default as PersonFill } from './other-16/sv-person-fill-icon.vue'
export { default as Dark } from './other-16/sv-dark-icon.vue'
export { default as Light } from './other-16/sv-light-icon.vue'
export { default as Discover } from './other-16/sv-discover-icon.vue'
export { default as Logouts } from './other-16/sv-logout-icon.vue'
export { default as Close } from './other-16/sv-close-icon.vue'
export { default as Expand } from './other-16/sv-expand-icon.vue'
export { default as Schedule } from './other-16/sv-schedule-icon.vue'
export { default as Star } from './other-16/sv-star-icon.vue'
export { default as StarFill } from './other-16/sv-star-fill-icon.vue'
export { default as Apps } from './other-16/sv-apps-icon.vue'
export { default as Send } from './other-16/sv-send-icon.vue'

export { default as GitHub } from './other/sv-github-icon.vue'
export { default as ArrowLine } from './other/sv-arrow-line-icon.vue'
